In [40]:
import pymongo
import pandas as pd

1. Write a Python program to connect to MySQL and print the list of all available databases.

In [41]:
from pymongo import MongoClient
client = MongoClient('localhost', 27017)
db = client['school_db']
from pymongo import MongoClient
print("Database created........")
print("List of databases after creating new one")
print(client.list_database_names())

Database created........
List of databases after creating new one
['admin', 'config', 'local', 'school_db']

2. Create a function in Python to create the tables (students, courses, enrollments) in school_db.
3. Write a Python program to insert multiple students and courses into the respective tables using executemany().

Students table created with csv data

In [42]:
df_s = db["students"]
students=pd.read_csv("./students.csv")
df_students = students.to_dict(orient="records")
df_s.insert_many(df_students)
print("CSV data uploaded successfully!")

CSV data uploaded successfully!

course table created with csv data

In [43]:
df_c = db["courses"]
courses=pd.read_csv("./courses.csv")
df_courses = courses.to_dict(orient="records")
df_c.insert_many(df_courses)
print("CSV data uploaded successfully!")

CSV data uploaded successfully!

enrollment table created with csv data

In [44]:
df_e = db["enrollment"]
enrollment=pd.read_csv("./enrollments.csv")
df_enrollment = enrollment.to_dict(orient="records")
df_e.insert_many(df_enrollment)
print("CSV data uploaded successfully!")

CSV data uploaded successfully!

4. Fetch and print all rows from the students table in a tabular format.

In [45]:
cursor = df_s.find()
for srows in cursor:
    print(srows)

{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b97'), 'student_id': 1, 'name': 'Zane1', 'age': 21, 'grade': 'C', 'email': 'zane1@school.edu', 'school_email': 'zane1479@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b99'), 'student_id': 3, 'name': 'Wendy3', 'age': 22, 'grade': 'B', 'email': 'wendy3@yahoo.com', 'school_email': 'wendy3dix@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9a'), 'student_id': 4, 'name': 'Xander4', 'age': 22, 'grade': 'A', 'email': 'xander4@outlook.com', 'school_email': 'xander4bnu@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9b'), 'student_id': 5, 'name': 'Victor5', 'age': 19, 'grade': 'A', 'email': 'victor5@gmail.com', 'school_email': 'victor5036@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9c'), 'student_id': 6, 'name': 'Ian6', 'age': 19, 'grade': 'D', 'email': 'ian6@outlook.com', 'school_email': 'ian616q@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9d'), 'student_id': 7, 'name': 'Leo7', 'age': 22, 'grade': 'A', 'email': 'leo7@gmail.com', 'school_email': 'leo7129@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9e'), 'student_id': 8, 'name': 'Paul8', 'age': 24, 'grade': 'B', 'email': 'paul8@outlook.com', 'school_email': 'paul8fjl@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b9f'), 'student_id': 9, 'name': 'Wendy9', 'age': 23, 'grade': 'B', 'email': 'wendy9@school.edu', 'school_email': 'wendy9mlh@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba0'), 'student_id': 10, 'name': 'Leo10', 'age': 23, 'grade': 'A', 'email': 'leo10@yahoo.com', 'school_email': 'leo10zdc@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba1'), 'student_id': 11, 'name': 'Uma11', 'age': 18, 'grade': 'C', 'email': 'uma11@school.edu', 'school_email': 'uma11jrp@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba2'), 'student_id': 12, 'name': 'Rita12', 'age': 18, 'grade': 'B', 'email': 'rita12@outlook.com', 'school_email': 'rita12b3o@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba3'), 'student_id': 13, 'name': 'Yara13', 'age': 22, 'grade': 'B', 'email': 'yara13@yahoo.com', 'school_email': 'yara13tu8@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba4'), 'student_id': 14, 'name': 'Bob14', 'age': 19, 'grade': 'C', 'email': 'bob14@outlook.com', 'school_email': 'bob14tpn@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba5'), 'student_id': 15, 'name': 'Quincy15', 'age': 24, 'grade': 'A', 'email': 'quincy15@school.edu', 'school_email': 'quincy15gt9@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba6'), 'student_id': 16, 'name': 'Tina16', 'age': 19, 'grade': 'A', 'email': 'tina16@yahoo.com', 'school_email': 'tina167ox@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba7'), 'student_id': 17, 'name': 'Alice17', 'age': 25, 'grade': 'B', 'email': 'alice17@outlook.com', 'school_email': 'alice17hmy@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba8'), 'student_id': 18, 'name': 'Sam18', 'age': 20, 'grade': 'B', 'email': 'sam18@gmail.com', 'school_email': 'sam18y87@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8ba9'), 'student_id': 19, 'name': 'Paul19', 'age': 23, 'grade': 'A', 'email': 'paul19@school.edu', 'school_email': 'paul19zj0@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8baa'), 'student_id': 20, 'name': 'Victor20', 'age': 19, 'grade': 'D', 'email': 'victor20@gmail.com', 'school_email': 'victor20gd6@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bab'), 'student_id': 21, 'name': 'Frank21', 'age': 23, 'grade': 'A', 'email': 'frank21@school.edu', 'school_email': 'frank21vhz@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bac'), 'student_id': 22, 'name': 'Victor22', 'age': 18, 'grade': 'A', 'email': 'victor22@yahoo.com', 'school_email': 'victor22k2z@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bad'), 'student_id': 23, 'name': 'Karen23', 'age': 25, 'grade': 'A', 'email': 'karen23@yahoo.com', 'school_email': 'karen2368z@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bae'), 'student_id': 24, 'name': 'Grace24', 'age': 24, 'grade': 'D', 'email': 'grace24@gmail.com', 'school_email': 'grace24t1b@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8baf'), 'student_id': 25, 'name': 'Quincy25', 'age': 25, 'grade': 'A', 'email': 'quincy25@school.edu', 'school_email': 'quincy25mc1@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb0'), 'student_id': 26, 'name': 'Mona26', 'age': 20, 'grade': 'D', 'email': 'mona26@gmail.com', 'school_email': 'mona26ilr@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb1'), 'student_id': 27, 'name': 'Uma27', 'age': 22, 'grade': 'B', 'email': 'uma27@school.edu', 'school_email': 'uma279sk@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb2'), 'student_id': 28, 'name': 'Nina28', 'age': 23, 'grade': 'B', 'email': 'nina28@yahoo.com', 'school_email': 'nina28jk7@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb3'), 'student_id': 29, 'name': 'Ian29', 'age': 23, 'grade': 'B', 'email': 'ian29@school.edu', 'school_email': 'ian292wp@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb4'), 'student_id': 30, 'name': 'Tina30', 'age': 23, 'grade': 'A', 'email': 'tina30@outlook.com', 'school_email': 'tina30z61@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb5'), 'student_id': 31, 'name': 'Nina31', 'age': 22, 'grade': 'B', 'email': 'nina31@school.edu', 'school_email': 'nina31ozi@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb6'), 'student_id': 32, 'name': 'Hannah32', 'age': 21, 'grade': 'A', 'email': 'hannah32@school.edu', 'school_email': 'hannah32ukv@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb7'), 'student_id': 33, 'name': 'David33', 'age': 25, 'grade': 'D', 'email': 'david33@school.edu', 'school_email': 'david33vn9@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb8'), 'student_id': 34, 'name': 'Wendy34', 'age': 22, 'grade': 'B', 'email': 'wendy34@yahoo.com', 'school_email': 'wendy34n2q@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bb9'), 'student_id': 35, 'name': 'Frank35', 'age': 25, 'grade': 'C', 'email': 'frank35@yahoo.com', 'school_email': 'frank35jgd@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bba'), 'student_id': 36, 'name': 'Paul36', 'age': 22, 'grade': 'D', 'email': 'paul36@outlook.com', 'school_email': 'paul36x7j@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bbb'), 'student_id': 37, 'name': 'Ian37', 'age': 21, 'grade': 'D', 'email': 'ian37@school.edu', 'school_email': 'ian372dd@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bbc'), 'student_id': 38, 'name': 'Paul38', 'age': 20, 'grade': 'C', 'email': 'paul38@outlook.com', 'school_email': 'paul38sen@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bbd'), 'student_id': 39, 'name': 'Hannah39', 'age': 18, 'grade': 'A', 'email': 'hannah39@outlook.com', 'school_email': 'hannah39icn@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bbe'), 'student_id': 40, 'name': 'Zane40', 'age': 21, 'grade': 'A', 'email': 'zane40@yahoo.com', 'school_email': 'zane4012c@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bbf'), 'student_id': 41, 'name': 'Ian41', 'age': 24, 'grade': 'D', 'email': 'ian41@outlook.com', 'school_email': 'ian41yj2@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc0'), 'student_id': 42, 'name': 'Quincy42', 'age': 24, 'grade': 'C', 'email': 'quincy42@gmail.com', 'school_email': 'quincy42mkj@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc1'), 'student_id': 43, 'name': 'Quincy43', 'age': 25, 'grade': 'D', 'email': 'quincy43@gmail.com', 'school_email': 'quincy43qsp@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc2'), 'student_id': 44, 'name': 'Tina44', 'age': 19, 'grade': 'C', 'email': 'tina44@outlook.com', 'school_email': 'tina44n0r@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc3'), 'student_id': 45, 'name': 'Xander45', 'age': 23, 'grade': 'C', 'email': 'xander45@yahoo.com', 'school_email': 'xander455xa@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc4'), 'student_id': 46, 'name': 'Zane46', 'age': 25, 'grade': 'C', 'email': 'zane46@gmail.com', 'school_email': 'zane46wz1@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc5'), 'student_id': 47, 'name': 'Eva47', 'age': 19, 'grade': 'D', 'email': 'eva47@yahoo.com', 'school_email': 'eva47br7@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc6'), 'student_id': 48, 'name': 'Leo48', 'age': 22, 'grade': 'B', 'email': 'leo48@outlook.com', 'school_email': 'leo48ydl@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc7'), 'student_id': 49, 'name': 'Uma49', 'age': 25, 'grade': 'A', 'email': 'uma49@school.edu', 'school_email': 'uma49k0i@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc8'), 'student_id': 50, 'name': 'Bob50', 'age': 22, 'grade': 'D', 'email': 'bob50@gmail.com', 'school_email': 'bob5040x@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bc9'), 'student_id': 51, 'name': 'Karen51', 'age': 18, 'grade': 'A', 'email': 'karen51@outlook.com', 'school_email': 'karen513k6@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bca'), 'student_id': 52, 'name': 'Hannah52', 'age': 23, 'grade': 'A', 'email': 'hannah52@yahoo.com', 'school_email': 'hannah52nhr@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bcb'), 'student_id': 53, 'name': 'Bob53', 'age': 21, 'grade': 'C', 'email': 'bob53@outlook.com', 'school_email': 'bob53rig@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bcc'), 'student_id': 54, 'name': 'Leo54', 'age': 18, 'grade': 'C', 'email': 'leo54@yahoo.com', 'school_email': 'leo544z2@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bcd'), 'student_id': 55, 'name': 'Yara55', 'age': 22, 'grade': 'A', 'email': 'yara55@yahoo.com', 'school_email': 'yara55wlz@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bce'), 'student_id': 56, 'name': 'Eva56', 'age': 19, 'grade': 'C', 'email': 'eva56@school.edu', 'school_email': 'eva560xg@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bcf'), 'student_id': 57, 'name': 'Nina57', 'age': 21, 'grade': 'B', 'email': 'nina57@school.edu', 'school_email': 'nina57rnd@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd0'), 'student_id': 58, 'name': 'Eva58', 'age': 20, 'grade': 'A', 'email': 'eva58@yahoo.com', 'school_email': 'eva58258@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd1'), 'student_id': 59, 'name': 'Oscar59', 'age': 21, 'grade': 'B', 'email': 'oscar59@yahoo.com', 'school_email': 'oscar59sxc@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd2'), 'student_id': 60, 'name': 'Yara60', 'age': 18, 'grade': 'B', 'email': 'yara60@gmail.com', 'school_email': 'yara60609@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd3'), 'student_id': 61, 'name': 'Oscar61', 'age': 23, 'grade': 'D', 'email': 'oscar61@gmail.com', 'school_email': 'oscar616ww@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd4'), 'student_id': 62, 'name': 'Rita62', 'age': 23, 'grade': 'C', 'email': 'rita62@gmail.com', 'school_email': 'rita62hst@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd5'), 'student_id': 63, 'name': 'Victor63', 'age': 20, 'grade': 'D', 'email': 'victor63@yahoo.com', 'school_email': 'victor63czq@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd6'), 'student_id': 64, 'name': 'Xander64', 'age': 19, 'grade': 'D', 'email': 'xander64@yahoo.com', 'school_email': 'xander64gwg@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd7'), 'student_id': 65, 'name': 'Hannah65', 'age': 22, 'grade': 'D', 'email': 'hannah65@school.edu', 'school_email': 'hannah65f4n@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd8'), 'student_id': 66, 'name': 'Nina66', 'age': 25, 'grade': 'D', 'email': 'nina66@school.edu', 'school_email': 'nina66nmi@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bd9'), 'student_id': 67, 'name': 'Victor67', 'age': 18, 'grade': 'A', 'email': 'victor67@outlook.com', 'school_email': 'victor67iri@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bda'), 'student_id': 68, 'name': 'Karen68', 'age': 18, 'grade': 'A', 'email': 'karen68@school.edu', 'school_email': 'karen68cx6@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bdb'), 'student_id': 69, 'name': 'Grace69', 'age': 18, 'grade': 'D', 'email': 'grace69@gmail.com', 'school_email': 'grace692y3@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bdc'), 'student_id': 70, 'name': 'Jack70', 'age': 24, 'grade': 'A', 'email': 'jack70@school.edu', 'school_email': 'jack70x70@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bdd'), 'student_id': 71, 'name': 'Nina71', 'age': 23, 'grade': 'B', 'email': 'nina71@outlook.com', 'school_email': 'nina71s6b@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bde'), 'student_id': 72, 'name': 'Ian72', 'age': 22, 'grade': 'D', 'email': 'ian72@gmail.com', 'school_email': 'ian72o27@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bdf'), 'student_id': 73, 'name': 'Grace73', 'age': 19, 'grade': 'A', 'email': 'grace73@yahoo.com', 'school_email': 'grace73pxa@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be0'), 'student_id': 74, 'name': 'Grace74', 'age': 24, 'grade': 'C', 'email': 'grace74@gmail.com', 'school_email': 'grace74phj@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be1'), 'student_id': 75, 'name': 'Quincy75', 'age': 23, 'grade': 'D', 'email': 'quincy75@school.edu', 'school_email': 'quincy75i1j@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be2'), 'student_id': 76, 'name': 'Oscar76', 'age': 19, 'grade': 'D', 'email': 'oscar76@school.edu', 'school_email': 'oscar760kr@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be3'), 'student_id': 77, 'name': 'Grace77', 'age': 22, 'grade': 'D', 'email': 'grace77@outlook.com', 'school_email': 'grace7739k@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be4'), 'student_id': 78, 'name': 'Ian78', 'age': 22, 'grade': 'D', 'email': 'ian78@outlook.com', 'school_email': 'ian78o1x@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be5'), 'student_id': 79, 'name': 'Xander79', 'age': 24, 'grade': 'C', 'email': 'xander79@outlook.com', 'school_email': 'xander791n9@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be6'), 'student_id': 80, 'name': 'Tina80', 'age': 22, 'grade': 'D', 'email': 'tina80@gmail.com', 'school_email': 'tina80qhf@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be7'), 'student_id': 81, 'name': 'Wendy81', 'age': 20, 'grade': 'A', 'email': 'wendy81@school.edu', 'school_email': 'wendy81pck@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be8'), 'student_id': 82, 'name': 'Karen82', 'age': 23, 'grade': 'B', 'email': 'karen82@outlook.com', 'school_email': 'karen82nh0@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8be9'), 'student_id': 83, 'name': 'Leo83', 'age': 18, 'grade': 'C', 'email': 'leo83@outlook.com', 'school_email': 'leo835b4@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bea'), 'student_id': 84, 'name': 'Bob84', 'age': 18, 'grade': 'A', 'email': 'bob84@school.edu', 'school_email': 'bob844dz@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8beb'), 'student_id': 85, 'name': 'Rita85', 'age': 18, 'grade': 'A', 'email': 'rita85@outlook.com', 'school_email': 'rita859ay@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bec'), 'student_id': 86, 'name': 'Alice86', 'age': 21, 'grade': 'B', 'email': 'alice86@outlook.com', 'school_email': 'alice86kze@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bed'), 'student_id': 87, 'name': 'Sam87', 'age': 19, 'grade': 'C', 'email': 'sam87@yahoo.com', 'school_email': 'sam87sci@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bee'), 'student_id': 88, 'name': 'Wendy88', 'age': 23, 'grade': 'A', 'email': 'wendy88@yahoo.com', 'school_email': 'wendy88cwj@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bef'), 'student_id': 89, 'name': 'Tina89', 'age': 21, 'grade': 'C', 'email': 'tina89@outlook.com', 'school_email': 'tina89lxc@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf0'), 'student_id': 90, 'name': 'Zane90', 'age': 25, 'grade': 'D', 'email': 'zane90@gmail.com', 'school_email': 'zane90zmc@yahoo.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf1'), 'student_id': 91, 'name': 'Tina91', 'age': 21, 'grade': 'D', 'email': 'tina91@yahoo.com', 'school_email': 'tina91fdv@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf2'), 'student_id': 92, 'name': 'Wendy92', 'age': 19, 'grade': 'C', 'email': 'wendy92@gmail.com', 'school_email': 'wendy92vwa@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf3'), 'student_id': 93, 'name': 'Quincy93', 'age': 19, 'grade': 'A', 'email': 'quincy93@gmail.com', 'school_email': 'quincy933uz@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf4'), 'student_id': 94, 'name': 'Eva94', 'age': 24, 'grade': 'C', 'email': 'eva94@school.edu', 'school_email': 'eva94l9w@example.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf5'), 'student_id': 95, 'name': 'Tina95', 'age': 25, 'grade': 'D', 'email': 'tina95@outlook.com', 'school_email': 'tina95cwj@outlook.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf6'), 'student_id': 96, 'name': 'Ian96', 'age': 25, 'grade': 'C', 'email': 'ian96@school.edu', 'school_email': 'ian9632h@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf7'), 'student_id': 97, 'name': 'Mona97', 'age': 22, 'grade': 'C', 'email': 'mona97@gmail.com', 'school_email': 'mona97z65@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf8'), 'student_id': 98, 'name': 'Leo98', 'age': 25, 'grade': 'A', 'email': 'leo98@school.edu', 'school_email': 'leo987fi@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bf9'), 'student_id': 99, 'name': 'Bob99', 'age': 23, 'grade': 'C', 'email': 'bob99@outlook.com', 'school_email': 'bob99iwn@gmail.com'}
{'_id': ObjectId('68c7f884b2f9bb8cdf5d8bfa'), 'student_id': 100, 'name': 'Paul100', 'age': 19, 'grade': 'B', 'email': 'paul100@outlook.com', 'school_email': 'paul100jpr@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8ccf'), 'student_id': 1, 'name': 'Zane1', 'age': 18, 'grade': 'C', 'email': 'zane1@school.edu'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd0'), 'student_id': 2, 'name': 'Uma2', 'age': 23, 'grade': 'A', 'email': 'uma2@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd1'), 'student_id': 3, 'name': 'Wendy3', 'age': 22, 'grade': 'B', 'email': 'wendy3@yahoo.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd2'), 'student_id': 4, 'name': 'Xander4', 'age': 22, 'grade': 'A', 'email': 'xander4@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd3'), 'student_id': 5, 'name': 'Victor5', 'age': 19, 'grade': 'A', 'email': 'victor5@gmail.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd4'), 'student_id': 6, 'name': 'Ian6', 'age': 19, 'grade': 'D', 'email': 'ian6@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd5'), 'student_id': 7, 'name': 'Leo7', 'age': 22, 'grade': 'A', 'email': 'leo7@gmail.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd6'), 'student_id': 8, 'name': 'Paul8', 'age': 24, 'grade': 'B', 'email': 'paul8@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd7'), 'student_id': 9, 'name': 'Wendy9', 'age': 23, 'grade': 'B', 'email': 'wendy9@school.edu'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd8'), 'student_id': 10, 'name': 'Leo10', 'age': 23, 'grade': 'A', 'email': 'leo10@yahoo.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cd9'), 'student_id': 11, 'name': 'Uma11', 'age': 18, 'grade': 'C', 'email': 'uma11@school.edu'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cda'), 'student_id': 12, 'name': 'Rita12', 'age': 18, 'grade': 'B', 'email': 'rita12@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cdb'), 'student_id': 13, 'name': 'Yara13', 'age': 22, 'grade': 'B', 'email': 'yara13@yahoo.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cdc'), 'student_id': 14, 'name': 'Bob14', 'age': 19, 'grade': 'C', 'email': 'bob14@outlook.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cdd'), 'student_id': 15, 'name': 'Quincy15', 'age': 24, 'grade': 'A', 'email': 'quincy15@school.edu'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cde'), 'student_id': 16, 'name': 'Tina16', 'age': 19, 'grade': 'A', 'email': 'tina16@yahoo.com'}
{'_id': ObjectId('68c81b0cb2f9bb8cdf5d8cdf'), 'student_id': 17, 'name': 'Alice17', 'age': 25, 'grade': 'B', 'email': 'alice17@outlook.com'}

5. Write a program to update the grade of a student (given student_id) via a Python input prompt.

In [46]:
df_s.update_one({"student_id": 1},{"$set": {"age": 21}})
print(df_s.find_one({"student_id": 1}))

{'_id': ObjectId('68c7f884b2f9bb8cdf5d8b97'), 'student_id': 1, 'name': 'Zane1', 'age': 21, 'grade': 'C', 'email': 'zane1@school.edu', 'school_email': 'zane1479@gmail.com'}

6. Delete a student from the students table using Python input for student_id.

In [47]:
df_s.delete_one({"name" : "Uma2"})

DeleteResult({'n': 1, 'ok': 1.0}, acknowledged=True)

7. Write a Python script to insert enrollment records linking students with their courses, ensuring foreign key integrity.

In [48]:
student_id = int(input("Enter Student ID: "))
course_id = int(input("Enter Course ID: "))

student = df_s.find_one({"student_id": student_id})
course = df_c.find_one({"course_id": course_id})


if student and course:
    df_e.insert_one({
        "student_id": student_id,
        "course_id": course_id
    })
    print("Enrollment added successfully!")
else:
    print("Error: Student or Course does not exist (foreign key check failed).")

Enrollment added successfully!

8. Fetch all students enrolled in a particular course (given course_id as input).

In [49]:
course_id = int(input("Enter course ID: "))

# Step 1: Find all enrollments for the course
enrollments = db.enrollment.find({"course_id": course_id}, {"student_id": 1, "_id": 0})

# Step 2: Fetch matching students
student_ids = [e["student_id"] for e in enrollments]

if student_ids:
    students = db.students.find({"student_id": {"$in": student_ids}}, {"_id": 0})
    print("\nStudents enrolled in course", course_id)
    for s in students:
        print(s)
else:
    print("No students enrolled in this course.")

Students enrolled in course 1
{'student_id': 1, 'name': 'Zane1', 'age': 21, 'grade': 'C', 'email': 'zane1@school.edu', 'school_email': 'zane1479@gmail.com'}
{'student_id': 7, 'name': 'Leo7', 'age': 22, 'grade': 'A', 'email': 'leo7@gmail.com', 'school_email': 'leo7129@outlook.com'}
{'student_id': 10, 'name': 'Leo10', 'age': 23, 'grade': 'A', 'email': 'leo10@yahoo.com', 'school_email': 'leo10zdc@example.com'}
{'student_id': 14, 'name': 'Bob14', 'age': 19, 'grade': 'C', 'email': 'bob14@outlook.com', 'school_email': 'bob14tpn@gmail.com'}
{'student_id': 16, 'name': 'Tina16', 'age': 19, 'grade': 'A', 'email': 'tina16@yahoo.com', 'school_email': 'tina167ox@example.com'}
{'student_id': 17, 'name': 'Alice17', 'age': 25, 'grade': 'B', 'email': 'alice17@outlook.com', 'school_email': 'alice17hmy@example.com'}
{'student_id': 19, 'name': 'Paul19', 'age': 23, 'grade': 'A', 'email': 'paul19@school.edu', 'school_email': 'paul19zj0@outlook.com'}
{'student_id': 26, 'name': 'Mona26', 'age': 20, 'grade': 'D', 'email': 'mona26@gmail.com', 'school_email': 'mona26ilr@yahoo.com'}
{'student_id': 28, 'name': 'Nina28', 'age': 23, 'grade': 'B', 'email': 'nina28@yahoo.com', 'school_email': 'nina28jk7@example.com'}
{'student_id': 30, 'name': 'Tina30', 'age': 23, 'grade': 'A', 'email': 'tina30@outlook.com', 'school_email': 'tina30z61@outlook.com'}
{'student_id': 46, 'name': 'Zane46', 'age': 25, 'grade': 'C', 'email': 'zane46@gmail.com', 'school_email': 'zane46wz1@gmail.com'}
{'student_id': 48, 'name': 'Leo48', 'age': 22, 'grade': 'B', 'email': 'leo48@outlook.com', 'school_email': 'leo48ydl@outlook.com'}
{'student_id': 58, 'name': 'Eva58', 'age': 20, 'grade': 'A', 'email': 'eva58@yahoo.com', 'school_email': 'eva58258@example.com'}
{'student_id': 61, 'name': 'Oscar61', 'age': 23, 'grade': 'D', 'email': 'oscar61@gmail.com', 'school_email': 'oscar616ww@example.com'}
{'student_id': 62, 'name': 'Rita62', 'age': 23, 'grade': 'C', 'email': 'rita62@gmail.com', 'school_email': 'rita62hst@gmail.com'}
{'student_id': 71, 'name': 'Nina71', 'age': 23, 'grade': 'B', 'email': 'nina71@outlook.com', 'school_email': 'nina71s6b@example.com'}
{'student_id': 74, 'name': 'Grace74', 'age': 24, 'grade': 'C', 'email': 'grace74@gmail.com', 'school_email': 'grace74phj@outlook.com'}
{'student_id': 77, 'name': 'Grace77', 'age': 22, 'grade': 'D', 'email': 'grace77@outlook.com', 'school_email': 'grace7739k@gmail.com'}
{'student_id': 81, 'name': 'Wendy81', 'age': 20, 'grade': 'A', 'email': 'wendy81@school.edu', 'school_email': 'wendy81pck@example.com'}
{'student_id': 89, 'name': 'Tina89', 'age': 21, 'grade': 'C', 'email': 'tina89@outlook.com', 'school_email': 'tina89lxc@yahoo.com'}
{'student_id': 91, 'name': 'Tina91', 'age': 21, 'grade': 'D', 'email': 'tina91@yahoo.com', 'school_email': 'tina91fdv@example.com'}
{'student_id': 92, 'name': 'Wendy92', 'age': 19, 'grade': 'C', 'email': 'wendy92@gmail.com', 'school_email': 'wendy92vwa@gmail.com'}
{'student_id': 1, 'name': 'Zane1', 'age': 18, 'grade': 'C', 'email': 'zane1@school.edu'}
{'student_id': 7, 'name': 'Leo7', 'age': 22, 'grade': 'A', 'email': 'leo7@gmail.com'}
{'student_id': 10, 'name': 'Leo10', 'age': 23, 'grade': 'A', 'email': 'leo10@yahoo.com'}
{'student_id': 14, 'name': 'Bob14', 'age': 19, 'grade': 'C', 'email': 'bob14@outlook.com'}
{'student_id': 16, 'name': 'Tina16', 'age': 19, 'grade': 'A', 'email': 'tina16@yahoo.com'}
{'student_id': 17, 'name': 'Alice17', 'age': 25, 'grade': 'B', 'email': 'alice17@outlook.com'}
{'student_id': 19, 'name': 'Paul19', 'age': 23, 'grade': 'A', 'email': 'paul19@school.edu'}
{'student_id': 26, 'name': 'Mona26', 'age': 20, 'grade': 'D', 'email': 'mona26@gmail.com'}
{'student_id': 28, 'name': 'Nina28', 'age': 23, 'grade': 'B', 'email': 'nina28@yahoo.com'}
{'student_id': 30, 'name': 'Tina30', 'age': 23, 'grade': 'A', 'email': 'tina30@outlook.com'}
{'student_id': 46, 'name': 'Zane46', 'age': 25, 'grade': 'C', 'email': 'zane46@gmail.com'}
{'student_id': 48, 'name': 'Leo48', 'age': 22, 'grade': 'B', 'email': 'leo48@outlook.com'}
{'student_id': 58, 'name': 'Eva58', 'age': 20, 'grade': 'A', 'email': 'eva58@yahoo.com'}
{'student_id': 61, 'name': 'Oscar61', 'age': 23, 'grade': 'D', 'email': 'oscar61@gmail.com'}
{'student_id': 62, 'name': 'Rita62', 'age': 23, 'grade': 'C', 'email': 'rita62@gmail.com'}
{'student_id': 71, 'name': 'Nina71', 'age': 23, 'grade': 'B', 'email': 'nina71@outlook.com'}
{'student_id': 74, 'name': 'Grace74', 'age': 24, 'grade': 'C', 'email': 'grace74@gmail.com'}
{'student_id': 77, 'name': 'Grace77', 'age': 22, 'grade': 'D', 'email': 'grace77@outlook.com'}
{'student_id': 81, 'name': 'Wendy81', 'age': 20, 'grade': 'A', 'email': 'wendy81@school.edu'}
{'student_id': 89, 'name': 'Tina89', 'age': 21, 'grade': 'C', 'email': 'tina89@outlook.com'}
{'student_id': 91, 'name': 'Tina91', 'age': 21, 'grade': 'D', 'email': 'tina91@yahoo.com'}
{'student_id': 92, 'name': 'Wendy92', 'age': 19, 'grade': 'C', 'email': 'wendy92@gmail.com'}

9. Write a program to display students who are not enrolled in any course.

In [50]:
pipeline = [
    {"$lookup": {
        "from": "enrollment",          
        "localField": "student_id",   
        "foreignField": "student_id",
        "as": "enrolled"
    }},
    {"$match": {"enrolled": {"$eq": []}}},
    {"$project": {"_id": 0, "student_id": 1, "name": 1}}
]

results = list(df_s.aggregate(pipeline))
if results:
    for r in results:
        print(r)
else:
    print("All students are enrolled in at least one course.")

All students are enrolled in at least one course.

10. Perform an INNER JOIN between students and courses using Python to show student names along with the courses they are enrolled in.

In [51]:
pipeline = [
    {"$lookup": {
        "from": "students",
        "localField": "student_id",
        "foreignField": "student_id",
        "as": "student_info"
    }},
    {"$unwind": "$student_info"},
    
    {"$lookup": {
        "from": "courses",
        "localField": "course_id",
        "foreignField": "course_id",
        "as": "course_info"
    }},
    {"$unwind": "$course_info"},
    
    {"$project": {
        "_id": 0,
        "student_name": "$student_info.name",
        "course_name": "$course_info.course_name"
    }}
]

results = list(df_e.aggregate(pipeline))
for r in results:
    print(f"{r['student_name']} → {r['course_name']}")

Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Wendy3 → English Literature
Wendy3 → English Literature
Wendy3 → English Literature
Wendy3 → English Literature
Xander4 → Statistics
Xander4 → Statistics
Xander4 → Statistics
Xander4 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Economics
Victor5 → Economics
Victor5 → Economics
Victor5 → Economics
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Biology
Ian6 → Biology
Ian6 → Biology
Ian6 → Biology
Ian6 → History
Ian6 → History
Ian6 → History
Ian6 → History
Leo7 → Mathematics
Leo7 → Mathematics
Leo7 → Mathematics
Leo7 → Mathematics
Paul8 → Philosophy
Paul8 → Philosophy
Paul8 → Philosophy
Paul8 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Mathematics
Leo10 → Mathematics
Leo10 → Mathematics
Leo10 → Mathematics
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Economics
Uma11 → Economics
Uma11 → Economics
Uma11 → Economics
Uma11 → English Literature
Uma11 → English Literature
Uma11 → English Literature
Uma11 → English Literature
Rita12 → Statistics
Rita12 → Statistics
Rita12 → Statistics
Rita12 → Statistics
Yara13 → Physics
Yara13 → Physics
Yara13 → Physics
Yara13 → Physics
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Statistics
Yara13 → Statistics
Yara13 → Statistics
Yara13 → Statistics
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Mathematics
Bob14 → Mathematics
Bob14 → Mathematics
Bob14 → Mathematics
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → History
Quincy15 → History
Quincy15 → History
Quincy15 → History
Quincy15 → Physics
Quincy15 → Physics
Quincy15 → Physics
Quincy15 → Physics
Tina16 → Economics
Tina16 → Economics
Tina16 → Economics
Tina16 → Economics
Tina16 → Biology
Tina16 → Biology
Tina16 → Biology
Tina16 → Biology
Tina16 → Mathematics
Tina16 → Mathematics
Tina16 → Mathematics
Tina16 → Mathematics
Alice17 → Economics
Alice17 → Economics
Alice17 → Economics
Alice17 → Economics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Computer Science
Alice17 → Computer Science
Alice17 → Computer Science
Alice17 → Computer Science
Sam18 → Chemistry
Sam18 → Chemistry
Sam18 → Chemistry
Sam18 → Chemistry
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Mathematics
Paul19 → Mathematics
Paul19 → Mathematics
Paul19 → Mathematics
Victor20 → English Literature
Victor20 → English Literature
Victor20 → English Literature
Victor20 → English Literature
Victor20 → Biology
Victor20 → Biology
Victor20 → Biology
Victor20 → Biology
Victor20 → Statistics
Victor20 → Statistics
Victor20 → Statistics
Victor20 → Statistics
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Economics
Frank21 → Economics
Frank21 → Economics
Frank21 → Economics
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Philosophy
Victor22 → Philosophy
Victor22 → Philosophy
Victor22 → Philosophy
Karen23 → History
Karen23 → History
Karen23 → History
Karen23 → History
Grace24 → Computer Science
Grace24 → Computer Science
Grace24 → Computer Science
Grace24 → Computer Science
Grace24 → English Literature
Grace24 → English Literature
Grace24 → English Literature
Grace24 → English Literature
Quincy25 → Philosophy
Quincy25 → Philosophy
Quincy25 → Philosophy
Quincy25 → Philosophy
Mona26 → Philosophy
Mona26 → Philosophy
Mona26 → Philosophy
Mona26 → Philosophy
Mona26 → English Literature
Mona26 → English Literature
Mona26 → English Literature
Mona26 → English Literature
Mona26 → Mathematics
Mona26 → Mathematics
Mona26 → Mathematics
Mona26 → Mathematics
Uma27 → Economics
Uma27 → Economics
Uma27 → Economics
Uma27 → Economics
Nina28 → Chemistry
Nina28 → Chemistry
Nina28 → Chemistry
Nina28 → Chemistry
Nina28 → Mathematics
Nina28 → Mathematics
Nina28 → Mathematics
Nina28 → Mathematics
Ian29 → History
Ian29 → History
Ian29 → History
Ian29 → History
Ian29 → Chemistry
Ian29 → Chemistry
Ian29 → Chemistry
Ian29 → Chemistry
Tina30 → Chemistry
Tina30 → Chemistry
Tina30 → Chemistry
Tina30 → Chemistry
Tina30 → Economics
Tina30 → Economics
Tina30 → Economics
Tina30 → Economics
Tina30 → Mathematics
Tina30 → Mathematics
Tina30 → Mathematics
Tina30 → Mathematics
Nina31 → Biology
Nina31 → Biology
Nina31 → Biology
Nina31 → Biology
Nina31 → Philosophy
Nina31 → Philosophy
Nina31 → Philosophy
Nina31 → Philosophy
Nina31 → Chemistry
Nina31 → Chemistry
Nina31 → Chemistry
Nina31 → Chemistry
Hannah32 → Biology
Hannah32 → Biology
Hannah32 → Biology
Hannah32 → Biology
Hannah32 → Philosophy
Hannah32 → Philosophy
Hannah32 → Philosophy
Hannah32 → Philosophy
David33 → History
David33 → History
David33 → History
David33 → History
David33 → Biology
David33 → Biology
David33 → Biology
David33 → Biology
Wendy34 → Chemistry
Wendy34 → Chemistry
Wendy34 → Chemistry
Wendy34 → Chemistry
Wendy34 → English Literature
Wendy34 → English Literature
Wendy34 → English Literature
Wendy34 → English Literature
Frank35 → Computer Science
Frank35 → Computer Science
Frank35 → Computer Science
Frank35 → Computer Science
Paul36 → Economics
Paul36 → Economics
Paul36 → Economics
Paul36 → Economics
Paul36 → Biology
Paul36 → Biology
Paul36 → Biology
Paul36 → Biology
Ian37 → Physics
Ian37 → Physics
Ian37 → Physics
Ian37 → Physics
Ian37 → Economics
Ian37 → Economics
Ian37 → Economics
Ian37 → Economics
Paul38 → Biology
Paul38 → Biology
Paul38 → Biology
Paul38 → Biology
Hannah39 → Economics
Hannah39 → Economics
Hannah39 → Economics
Hannah39 → Economics
Zane40 → Biology
Zane40 → Biology
Zane40 → Biology
Zane40 → Biology
Ian41 → Statistics
Ian41 → Statistics
Ian41 → Statistics
Ian41 → Statistics
Ian41 → Chemistry
Ian41 → Chemistry
Ian41 → Chemistry
Ian41 → Chemistry
Quincy42 → Statistics
Quincy42 → Statistics
Quincy42 → Statistics
Quincy42 → Statistics
Quincy42 → History
Quincy42 → History
Quincy42 → History
Quincy42 → History
Quincy42 → Computer Science
Quincy42 → Computer Science
Quincy42 → Computer Science
Quincy42 → Computer Science
Quincy43 → Physics
Quincy43 → Physics
Quincy43 → Physics
Quincy43 → Physics
Tina44 → Philosophy
Tina44 → Philosophy
Tina44 → Philosophy
Tina44 → Philosophy
Xander45 → Economics
Xander45 → Economics
Xander45 → Economics
Xander45 → Economics
Xander45 → History
Xander45 → History
Xander45 → History
Xander45 → History
Xander45 → Statistics
Xander45 → Statistics
Xander45 → Statistics
Xander45 → Statistics
Zane46 → Mathematics
Zane46 → Mathematics
Zane46 → Mathematics
Zane46 → Mathematics
Zane46 → Statistics
Zane46 → Statistics
Zane46 → Statistics
Zane46 → Statistics
Zane46 → History
Zane46 → History
Zane46 → History
Zane46 → History
Eva47 → Physics
Eva47 → Physics
Eva47 → Physics
Eva47 → Physics
Leo48 → Mathematics
Leo48 → Mathematics
Leo48 → Mathematics
Leo48 → Mathematics
Leo48 → Biology
Leo48 → Biology
Leo48 → Biology
Leo48 → Biology
Leo48 → Statistics
Leo48 → Statistics
Leo48 → Statistics
Leo48 → Statistics
Uma49 → Biology
Uma49 → Biology
Uma49 → Biology
Uma49 → Biology
Uma49 → Computer Science
Uma49 → Computer Science
Uma49 → Computer Science
Uma49 → Computer Science
Bob50 → Computer Science
Bob50 → Computer Science
Bob50 → Computer Science
Bob50 → Computer Science
Karen51 → Computer Science
Karen51 → Computer Science
Karen51 → Computer Science
Karen51 → Computer Science
Karen51 → English Literature
Karen51 → English Literature
Karen51 → English Literature
Karen51 → English Literature
Karen51 → Biology
Karen51 → Biology
Karen51 → Biology
Karen51 → Biology
Hannah52 → Physics
Hannah52 → Physics
Hannah52 → Physics
Hannah52 → Physics
Hannah52 → Chemistry
Hannah52 → Chemistry
Hannah52 → Chemistry
Hannah52 → Chemistry
Bob53 → Physics
Bob53 → Physics
Bob53 → Physics
Bob53 → Physics
Bob53 → History
Bob53 → History
Bob53 → History
Bob53 → History
Bob53 → Biology
Bob53 → Biology
Bob53 → Biology
Bob53 → Biology
Leo54 → Chemistry
Leo54 → Chemistry
Leo54 → Chemistry
Leo54 → Chemistry
Leo54 → Philosophy
Leo54 → Philosophy
Leo54 → Philosophy
Leo54 → Philosophy
Leo54 → History
Leo54 → History
Leo54 → History
Leo54 → History
Yara55 → Economics
Yara55 → Economics
Yara55 → Economics
Yara55 → Economics
Yara55 → Statistics
Yara55 → Statistics
Yara55 → Statistics
Yara55 → Statistics
Yara55 → Philosophy
Yara55 → Philosophy
Yara55 → Philosophy
Yara55 → Philosophy
Eva56 → Economics
Eva56 → Economics
Eva56 → Economics
Eva56 → Economics
Nina57 → Physics
Nina57 → Physics
Nina57 → Physics
Nina57 → Physics
Nina57 → Computer Science
Nina57 → Computer Science
Nina57 → Computer Science
Nina57 → Computer Science
Nina57 → History
Nina57 → History
Nina57 → History
Nina57 → History
Eva58 → Mathematics
Eva58 → Mathematics
Eva58 → Mathematics
Eva58 → Mathematics
Oscar59 → Philosophy
Oscar59 → Philosophy
Oscar59 → Philosophy
Oscar59 → Philosophy
Oscar59 → English Literature
Oscar59 → English Literature
Oscar59 → English Literature
Oscar59 → English Literature
Oscar59 → Statistics
Oscar59 → Statistics
Oscar59 → Statistics
Oscar59 → Statistics
Yara60 → Physics
Yara60 → Physics
Yara60 → Physics
Yara60 → Physics
Yara60 → Biology
Yara60 → Biology
Yara60 → Biology
Yara60 → Biology
Oscar61 → Mathematics
Oscar61 → Mathematics
Oscar61 → Mathematics
Oscar61 → Mathematics
Rita62 → Mathematics
Rita62 → Mathematics
Rita62 → Mathematics
Rita62 → Mathematics
Victor63 → History
Victor63 → History
Victor63 → History
Victor63 → History
Xander64 → Chemistry
Xander64 → Chemistry
Xander64 → Chemistry
Xander64 → Chemistry
Xander64 → Philosophy
Xander64 → Philosophy
Xander64 → Philosophy
Xander64 → Philosophy
Xander64 → Biology
Xander64 → Biology
Xander64 → Biology
Xander64 → Biology
Hannah65 → Chemistry
Hannah65 → Chemistry
Hannah65 → Chemistry
Hannah65 → Chemistry
Nina66 → Chemistry
Nina66 → Chemistry
Nina66 → Chemistry
Nina66 → Chemistry
Nina66 → Biology
Nina66 → Biology
Nina66 → Biology
Nina66 → Biology
Nina66 → Economics
Nina66 → Economics
Nina66 → Economics
Nina66 → Economics
Victor67 → Computer Science
Victor67 → Computer Science
Victor67 → Computer Science
Victor67 → Computer Science
Karen68 → Chemistry
Karen68 → Chemistry
Karen68 → Chemistry
Karen68 → Chemistry
Grace69 → Economics
Grace69 → Economics
Grace69 → Economics
Grace69 → Economics
Grace69 → English Literature
Grace69 → English Literature
Grace69 → English Literature
Grace69 → English Literature
Grace69 → Chemistry
Grace69 → Chemistry
Grace69 → Chemistry
Grace69 → Chemistry
Jack70 → Computer Science
Jack70 → Computer Science
Jack70 → Computer Science
Jack70 → Computer Science
Jack70 → Statistics
Jack70 → Statistics
Jack70 → Statistics
Jack70 → Statistics
Nina71 → History
Nina71 → History
Nina71 → History
Nina71 → History
Nina71 → Mathematics
Nina71 → Mathematics
Nina71 → Mathematics
Nina71 → Mathematics
Ian72 → Chemistry
Ian72 → Chemistry
Ian72 → Chemistry
Ian72 → Chemistry
Ian72 → Computer Science
Ian72 → Computer Science
Ian72 → Computer Science
Ian72 → Computer Science
Ian72 → Philosophy
Ian72 → Philosophy
Ian72 → Philosophy
Ian72 → Philosophy
Grace73 → Computer Science
Grace73 → Computer Science
Grace73 → Computer Science
Grace73 → Computer Science
Grace73 → Statistics
Grace73 → Statistics
Grace73 → Statistics
Grace73 → Statistics
Grace74 → Economics
Grace74 → Economics
Grace74 → Economics
Grace74 → Economics
Grace74 → Mathematics
Grace74 → Mathematics
Grace74 → Mathematics
Grace74 → Mathematics
Grace74 → Computer Science
Grace74 → Computer Science
Grace74 → Computer Science
Grace74 → Computer Science
Quincy75 → Physics
Quincy75 → Physics
Quincy75 → Physics
Quincy75 → Physics
Quincy75 → History
Quincy75 → History
Quincy75 → History
Quincy75 → History
Oscar76 → Computer Science
Oscar76 → Computer Science
Oscar76 → Computer Science
Oscar76 → Computer Science
Oscar76 → English Literature
Oscar76 → English Literature
Oscar76 → English Literature
Oscar76 → English Literature
Oscar76 → Philosophy
Oscar76 → Philosophy
Oscar76 → Philosophy
Oscar76 → Philosophy
Grace77 → Biology
Grace77 → Biology
Grace77 → Biology
Grace77 → Biology
Grace77 → Economics
Grace77 → Economics
Grace77 → Economics
Grace77 → Economics
Grace77 → Mathematics
Grace77 → Mathematics
Grace77 → Mathematics
Grace77 → Mathematics
Ian78 → Physics
Ian78 → Physics
Ian78 → Physics
Ian78 → Physics
Ian78 → Philosophy
Ian78 → Philosophy
Ian78 → Philosophy
Ian78 → Philosophy
Ian78 → Statistics
Ian78 → Statistics
Ian78 → Statistics
Ian78 → Statistics
Xander79 → Chemistry
Xander79 → Chemistry
Xander79 → Chemistry
Xander79 → Chemistry
Xander79 → History
Xander79 → History
Xander79 → History
Xander79 → History
Tina80 → History
Tina80 → History
Tina80 → History
Tina80 → History
Wendy81 → Mathematics
Wendy81 → Mathematics
Wendy81 → Mathematics
Wendy81 → Mathematics
Wendy81 → History
Wendy81 → History
Wendy81 → History
Wendy81 → History
Wendy81 → Economics
Wendy81 → Economics
Wendy81 → Economics
Wendy81 → Economics
Karen82 → Chemistry
Karen82 → Chemistry
Karen82 → Chemistry
Karen82 → Chemistry
Leo83 → Philosophy
Leo83 → Philosophy
Leo83 → Philosophy
Leo83 → Philosophy
Leo83 → Chemistry
Leo83 → Chemistry
Leo83 → Chemistry
Leo83 → Chemistry
Leo83 → Physics
Leo83 → Physics
Leo83 → Physics
Leo83 → Physics
Bob84 → History
Bob84 → History
Bob84 → History
Bob84 → History
Bob84 → Chemistry
Bob84 → Chemistry
Bob84 → Chemistry
Bob84 → Chemistry
Rita85 → Computer Science
Rita85 → Computer Science
Rita85 → Computer Science
Rita85 → Computer Science
Alice86 → Chemistry
Alice86 → Chemistry
Alice86 → Chemistry
Alice86 → Chemistry
Sam87 → Statistics
Sam87 → Statistics
Sam87 → Statistics
Sam87 → Statistics
Sam87 → Philosophy
Sam87 → Philosophy
Sam87 → Philosophy
Sam87 → Philosophy
Sam87 → English Literature
Sam87 → English Literature
Sam87 → English Literature
Sam87 → English Literature
Wendy88 → History
Wendy88 → History
Wendy88 → History
Wendy88 → History
Tina89 → Mathematics
Tina89 → Mathematics
Tina89 → Mathematics
Tina89 → Mathematics
Zane90 → Physics
Zane90 → Physics
Zane90 → Physics
Zane90 → Physics
Tina91 → Biology
Tina91 → Biology
Tina91 → Biology
Tina91 → Biology
Tina91 → Mathematics
Tina91 → Mathematics
Tina91 → Mathematics
Tina91 → Mathematics
Tina91 → Physics
Tina91 → Physics
Tina91 → Physics
Tina91 → Physics
Wendy92 → Computer Science
Wendy92 → Computer Science
Wendy92 → Computer Science
Wendy92 → Computer Science
Wendy92 → Mathematics
Wendy92 → Mathematics
Wendy92 → Mathematics
Wendy92 → Mathematics
Wendy92 → English Literature
Wendy92 → English Literature
Wendy92 → English Literature
Wendy92 → English Literature
Quincy93 → Computer Science
Quincy93 → Computer Science
Quincy93 → Computer Science
Quincy93 → Computer Science
Quincy93 → Chemistry
Quincy93 → Chemistry
Quincy93 → Chemistry
Quincy93 → Chemistry
Eva94 → Economics
Eva94 → Economics
Eva94 → Economics
Eva94 → Economics
Eva94 → Statistics
Eva94 → Statistics
Eva94 → Statistics
Eva94 → Statistics
Tina95 → Chemistry
Tina95 → Chemistry
Tina95 → Chemistry
Tina95 → Chemistry
Ian96 → Philosophy
Ian96 → Philosophy
Ian96 → Philosophy
Ian96 → Philosophy
Ian96 → History
Ian96 → History
Ian96 → History
Ian96 → History
Ian96 → Physics
Ian96 → Physics
Ian96 → Physics
Ian96 → Physics
Mona97 → History
Mona97 → History
Mona97 → History
Mona97 → History
Leo98 → Philosophy
Leo98 → Philosophy
Leo98 → Philosophy
Leo98 → Philosophy
Leo98 → Chemistry
Leo98 → Chemistry
Leo98 → Chemistry
Leo98 → Chemistry
Bob99 → Computer Science
Bob99 → Computer Science
Bob99 → Computer Science
Bob99 → Computer Science
Bob99 → Physics
Bob99 → Physics
Bob99 → Physics
Bob99 → Physics
Paul100 → Philosophy
Paul100 → Philosophy
Paul100 → Philosophy
Paul100 → Philosophy
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Zane1 → Statistics
Wendy3 → English Literature
Wendy3 → English Literature
Wendy3 → English Literature
Wendy3 → English Literature
Xander4 → Statistics
Xander4 → Statistics
Xander4 → Statistics
Xander4 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Statistics
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Chemistry
Victor5 → Economics
Victor5 → Economics
Victor5 → Economics
Victor5 → Economics
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Computer Science
Ian6 → Biology
Ian6 → Biology
Ian6 → Biology
Ian6 → Biology
Ian6 → History
Ian6 → History
Ian6 → History
Ian6 → History
Leo7 → Mathematics
Leo7 → Mathematics
Leo7 → Mathematics
Leo7 → Mathematics
Paul8 → Philosophy
Paul8 → Philosophy
Paul8 → Philosophy
Paul8 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Wendy9 → Philosophy
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Computer Science
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Chemistry
Leo10 → Mathematics
Leo10 → Mathematics
Leo10 → Mathematics
Leo10 → Mathematics
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Chemistry
Uma11 → Economics
Uma11 → Economics
Uma11 → Economics
Uma11 → Economics
Uma11 → English Literature
Uma11 → English Literature
Uma11 → English Literature
Uma11 → English Literature
Rita12 → Statistics
Rita12 → Statistics
Rita12 → Statistics
Rita12 → Statistics
Yara13 → Physics
Yara13 → Physics
Yara13 → Physics
Yara13 → Physics
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Philosophy
Yara13 → Statistics
Yara13 → Statistics
Yara13 → Statistics
Yara13 → Statistics
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Chemistry
Bob14 → Mathematics
Bob14 → Mathematics
Bob14 → Mathematics
Bob14 → Mathematics
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → English Literature
Quincy15 → History
Quincy15 → History
Quincy15 → History
Quincy15 → History
Quincy15 → Physics
Quincy15 → Physics
Quincy15 → Physics
Quincy15 → Physics
Tina16 → Economics
Tina16 → Economics
Tina16 → Economics
Tina16 → Economics
Tina16 → Biology
Tina16 → Biology
Tina16 → Biology
Tina16 → Biology
Tina16 → Mathematics
Tina16 → Mathematics
Tina16 → Mathematics
Tina16 → Mathematics
Alice17 → Economics
Alice17 → Economics
Alice17 → Economics
Alice17 → Economics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Mathematics
Alice17 → Computer Science
Alice17 → Computer Science
Alice17 → Computer Science
Alice17 → Computer Science
Sam18 → Chemistry
Sam18 → Chemistry
Sam18 → Chemistry
Sam18 → Chemistry
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Philosophy
Paul19 → Mathematics
Paul19 → Mathematics
Paul19 → Mathematics
Paul19 → Mathematics
Victor20 → English Literature
Victor20 → English Literature
Victor20 → English Literature
Victor20 → English Literature
Victor20 → Biology
Victor20 → Biology
Victor20 → Biology
Victor20 → Biology
Victor20 → Statistics
Victor20 → Statistics
Victor20 → Statistics
Victor20 → Statistics
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Computer Science
Frank21 → Economics
Frank21 → Economics
Frank21 → Economics
Frank21 → Economics
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Chemistry
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Statistics
Victor22 → Philosophy
Victor22 → Philosophy
Victor22 → Philosophy
Victor22 → Philosophy
Karen23 → History
Karen23 → History

11. Write a Python function to search for a student by name (partial matches allowed using LIKE).

In [52]:
results = list(df_s.find(student, {"_id": 0, "student_id": 1, "name": 1, "grade": 1}))
if results:
    for r in results:
            print(f"ID: {r['student_id']} | Name: {r['name']} | Grade: {r['grade']}")
else:
        print(f"No students found matching .")

ID: 1 | Name: Zane1 | Grade: C

12. Add a new column email to the students table using Python and update it with random values.

In [53]:
import numpy as np

domains = ["gmail.com", "yahoo.com", "outlook.com", "example.com"]
chars = list("abcdefghijklmnopqrstuvwxyz0123456789")

for s in df_s.find({}, {"_id": 0, "student_id": 1, "name": 1}):
    random_str = ''.join(np.random.choice(chars, 3))
    domain = np.random.choice(domains)
    school_email = f"{s['name'].lower()}{random_str}@{domain}"

    df_s.update_one(
        {"student_id": s["student_id"]},
        {"$set": {"school_email": school_email}}
    )

print("Emails added successfully!")

for s in df_s.find({}, {"_id": 0, "student_id": 1, "name": 1, "email": 1}):
    print(s)

Emails added successfully!
{'student_id': 1, 'name': 'Zane1', 'email': 'zane1@school.edu'}
{'student_id': 3, 'name': 'Wendy3', 'email': 'wendy3@yahoo.com'}
{'student_id': 4, 'name': 'Xander4', 'email': 'xander4@outlook.com'}
{'student_id': 5, 'name': 'Victor5', 'email': 'victor5@gmail.com'}
{'student_id': 6, 'name': 'Ian6', 'email': 'ian6@outlook.com'}
{'student_id': 7, 'name': 'Leo7', 'email': 'leo7@gmail.com'}
{'student_id': 8, 'name': 'Paul8', 'email': 'paul8@outlook.com'}
{'student_id': 9, 'name': 'Wendy9', 'email': 'wendy9@school.edu'}
{'student_id': 10, 'name': 'Leo10', 'email': 'leo10@yahoo.com'}
{'student_id': 11, 'name': 'Uma11', 'email': 'uma11@school.edu'}
{'student_id': 12, 'name': 'Rita12', 'email': 'rita12@outlook.com'}
{'student_id': 13, 'name': 'Yara13', 'email': 'yara13@yahoo.com'}
{'student_id': 14, 'name': 'Bob14', 'email': 'bob14@outlook.com'}
{'student_id': 15, 'name': 'Quincy15', 'email': 'quincy15@school.edu'}
{'student_id': 16, 'name': 'Tina16', 'email': 'tina16@yahoo.com'}
{'student_id': 17, 'name': 'Alice17', 'email': 'alice17@outlook.com'}
{'student_id': 18, 'name': 'Sam18', 'email': 'sam18@gmail.com'}
{'student_id': 19, 'name': 'Paul19', 'email': 'paul19@school.edu'}
{'student_id': 20, 'name': 'Victor20', 'email': 'victor20@gmail.com'}
{'student_id': 21, 'name': 'Frank21', 'email': 'frank21@school.edu'}
{'student_id': 22, 'name': 'Victor22', 'email': 'victor22@yahoo.com'}
{'student_id': 23, 'name': 'Karen23', 'email': 'karen23@yahoo.com'}
{'student_id': 24, 'name': 'Grace24', 'email': 'grace24@gmail.com'}
{'student_id': 25, 'name': 'Quincy25', 'email': 'quincy25@school.edu'}
{'student_id': 26, 'name': 'Mona26', 'email': 'mona26@gmail.com'}
{'student_id': 27, 'name': 'Uma27', 'email': 'uma27@school.edu'}
{'student_id': 28, 'name': 'Nina28', 'email': 'nina28@yahoo.com'}
{'student_id': 29, 'name': 'Ian29', 'email': 'ian29@school.edu'}
{'student_id': 30, 'name': 'Tina30', 'email': 'tina30@outlook.com'}
{'student_id': 31, 'name': 'Nina31', 'email': 'nina31@school.edu'}
{'student_id': 32, 'name': 'Hannah32', 'email': 'hannah32@school.edu'}
{'student_id': 33, 'name': 'David33', 'email': 'david33@school.edu'}
{'student_id': 34, 'name': 'Wendy34', 'email': 'wendy34@yahoo.com'}
{'student_id': 35, 'name': 'Frank35', 'email': 'frank35@yahoo.com'}
{'student_id': 36, 'name': 'Paul36', 'email': 'paul36@outlook.com'}
{'student_id': 37, 'name': 'Ian37', 'email': 'ian37@school.edu'}
{'student_id': 38, 'name': 'Paul38', 'email': 'paul38@outlook.com'}
{'student_id': 39, 'name': 'Hannah39', 'email': 'hannah39@outlook.com'}
{'student_id': 40, 'name': 'Zane40', 'email': 'zane40@yahoo.com'}
{'student_id': 41, 'name': 'Ian41', 'email': 'ian41@outlook.com'}
{'student_id': 42, 'name': 'Quincy42', 'email': 'quincy42@gmail.com'}
{'student_id': 43, 'name': 'Quincy43', 'email': 'quincy43@gmail.com'}
{'student_id': 44, 'name': 'Tina44', 'email': 'tina44@outlook.com'}
{'student_id': 45, 'name': 'Xander45', 'email': 'xander45@yahoo.com'}
{'student_id': 46, 'name': 'Zane46', 'email': 'zane46@gmail.com'}
{'student_id': 47, 'name': 'Eva47', 'email': 'eva47@yahoo.com'}
{'student_id': 48, 'name': 'Leo48', 'email': 'leo48@outlook.com'}
{'student_id': 49, 'name': 'Uma49', 'email': 'uma49@school.edu'}
{'student_id': 50, 'name': 'Bob50', 'email': 'bob50@gmail.com'}
{'student_id': 51, 'name': 'Karen51', 'email': 'karen51@outlook.com'}
{'student_id': 52, 'name': 'Hannah52', 'email': 'hannah52@yahoo.com'}
{'student_id': 53, 'name': 'Bob53', 'email': 'bob53@outlook.com'}
{'student_id': 54, 'name': 'Leo54', 'email': 'leo54@yahoo.com'}
{'student_id': 55, 'name': 'Yara55', 'email': 'yara55@yahoo.com'}
{'student_id': 56, 'name': 'Eva56', 'email': 'eva56@school.edu'}
{'student_id': 57, 'name': 'Nina57', 'email': 'nina57@school.edu'}
{'student_id': 58, 'name': 'Eva58', 'email': 'eva58@yahoo.com'}
{'student_id': 59, 'name': 'Oscar59', 'email': 'oscar59@yahoo.com'}
{'student_id': 60, 'name': 'Yara60', 'email': 'yara60@gmail.com'}
{'student_id': 61, 'name': 'Oscar61', 'email': 'oscar61@gmail.com'}
{'student_id': 62, 'name': 'Rita62', 'email': 'rita62@gmail.com'}
{'student_id': 63, 'name': 'Victor63', 'email': 'victor63@yahoo.com'}
{'student_id': 64, 'name': 'Xander64', 'email': 'xander64@yahoo.com'}
{'student_id': 65, 'name': 'Hannah65', 'email': 'hannah65@school.edu'}
{'student_id': 66, 'name': 'Nina66', 'email': 'nina66@school.edu'}
{'student_id': 67, 'name': 'Victor67', 'email': 'victor67@outlook.com'}
{'student_id': 68, 'name': 'Karen68', 'email': 'karen68@school.edu'}
{'student_id': 69, 'name': 'Grace69', 'email': 'grace69@gmail.com'}
{'student_id': 70, 'name': 'Jack70', 'email': 'jack70@school.edu'}
{'student_id': 71, 'name': 'Nina71', 'email': 'nina71@outlook.com'}
{'student_id': 72, 'name': 'Ian72', 'email': 'ian72@gmail.com'}
{'student_id': 73, 'name': 'Grace73', 'email': 'grace73@yahoo.com'}
{'student_id': 74, 'name': 'Grace74', 'email': 'grace74@gmail.com'}
{'student_id': 75, 'name': 'Quincy75', 'email': 'quincy75@school.edu'}
{'student_id': 76, 'name': 'Oscar76', 'email': 'oscar76@school.edu'}
{'student_id': 77, 'name': 'Grace77', 'email': 'grace77@outlook.com'}
{'student_id': 78, 'name': 'Ian78', 'email': 'ian78@outlook.com'}
{'student_id': 79, 'name': 'Xander79', 'email': 'xander79@outlook.com'}
{'student_id': 80, 'name': 'Tina80', 'email': 'tina80@gmail.com'}
{'student_id': 81, 'name': 'Wendy81', 'email': 'wendy81@school.edu'}
{'student_id': 82, 'name': 'Karen82', 'email': 'karen82@outlook.com'}
{'student_id': 83, 'name': 'Leo83', 'email': 'leo83@outlook.com'}
{'student_id': 84, 'name': 'Bob84', 'email': 'bob84@school.edu'}
{'student_id': 85, 'name': 'Rita85', 'email': 'rita85@outlook.com'}
{'student_id': 86, 'name': 'Alice86', 'email': 'alice86@outlook.com'}
{'student_id': 87, 'name': 'Sam87', 'email': 'sam87@yahoo.com'}
{'student_id': 88, 'name': 'Wendy88', 'email': 'wendy88@yahoo.com'}
{'student_id': 89, 'name': 'Tina89', 'email': 'tina89@outlook.com'}
{'student_id': 90, 'name': 'Zane90', 'email': 'zane90@gmail.com'}
{'student_id': 91, 'name': 'Tina91', 'email': 'tina91@yahoo.com'}
{'student_id': 92, 'name': 'Wendy92', 'email': 'wendy92@gmail.com'}
{'student_id': 93, 'name': 'Quincy93', 'email': 'quincy93@gmail.com'}
{'student_id': 94, 'name': 'Eva94', 'email': 'eva94@school.edu'}
{'student_id': 95, 'name': 'Tina95', 'email': 'tina95@outlook.com'}
{'student_id': 96, 'name': 'Ian96', 'email': 'ian96@school.edu'}
{'student_id': 97, 'name': 'Mona97', 'email': 'mona97@gmail.com'}
{'student_id': 98, 'name': 'Leo98', 'email': 'leo98@school.edu'}
{'student_id': 99, 'name': 'Bob99', 'email': 'bob99@outlook.com'}
{'student_id': 100, 'name': 'Paul100', 'email': 'paul100@outlook.com'}
{'student_id': 1, 'name': 'Zane1', 'email': 'zane1@school.edu'}
{'student_id': 3, 'name': 'Wendy3', 'email': 'wendy3@yahoo.com'}
{'student_id': 4, 'name': 'Xander4', 'email': 'xander4@outlook.com'}
{'student_id': 5, 'name': 'Victor5', 'email': 'victor5@gmail.com'}
{'student_id': 6, 'name': 'Ian6', 'email': 'ian6@outlook.com'}
{'student_id': 7, 'name': 'Leo7', 'email': 'leo7@gmail.com'}
{'student_id': 8, 'name': 'Paul8', 'email': 'paul8@outlook.com'}
{'student_id': 9, 'name': 'Wendy9', 'email': 'wendy9@school.edu'}
{'student_id': 10, 'name': 'Leo10', 'email': 'leo10@yahoo.com'}
{'student_id': 11, 'name': 'Uma11', 'email': 'uma11@school.edu'}
{'student_id': 12, 'name': 'Rita12', 'email': 'rita12@outlook.com'}
{'student_id': 13, 'name': 'Yara13', 'email': 'yara13@yahoo.com'}
{'student_id': 14, 'name': 'Bob14', 'email': 'bob14@outlook.com'}
{'student_id': 15, 'name': 'Quincy15', 'email': 'quincy15@school.edu'}
{'student_id': 16, 'name': 'Tina16', 'email': 'tina16@yahoo.com'}
{'student_id': 17, 'name': 'Alice17', 'email': 'alice17@outlook.com'}
{'student_id': 18, 'name': 'Sam18', 'email': 'sam18@gmail.com'}
{'student_id': 19, 'name': 'Paul19', 'email': 'paul19@school.edu'}
{'student_id': 20, 'name': 'Victor20', 'email': 'victor20@gmail.com'}
{'student_id': 21, 'name': 'Frank21', 'email': 'frank21@school.edu'}
{'student_id': 22, 'name': 'Victor22', 'email': 'victor22@yahoo.com'}
{'student_id': 23, 'name': 'Karen23', 'email': 'karen23@yahoo.com'}
{'student_id': 24, 'name': 'Grace24', 'email': 'grace24@gmail.com'}
{'student_id': 25, 'name': 'Quincy25', 'email': 'quincy25@school.edu'}
{'student_id': 26, 'name': 'Mona26', 'email': 'mona26@gmail.com'}
{'student_id': 27, 'name': 'Uma27', 'email': 'uma27@school.edu'}
{'student_id': 28, 'name': 'Nina28', 'email': 'nina28@yahoo.com'}
{'student_id': 29, 'name': 'Ian29', 'email': 'ian29@school.edu'}
{'student_id': 30, 'name': 'Tina30', 'email': 'tina30@outlook.com'}
{'student_id': 31, 'name': 'Nina31', 'email': 'nina31@school.edu'}
{'student_id': 32, 'name': 'Hannah32', 'email': 'hannah32@school.edu'}
{'student_id': 33, 'name': 'David33', 'email': 'david33@school.edu'}
{'student_id': 34, 'name': 'Wendy34', 'email': 'wendy34@yahoo.com'}
{'student_id': 35, 'name': 'Frank35', 'email': 'frank35@yahoo.com'}
{'student_id': 36, 'name': 'Paul36', 'email': 'paul36@outlook.com'}
{'student_id': 37, 'name': 'Ian37', 'email': 'ian37@school.edu'}
{'student_id': 38, 'name': 'Paul38', 'email': 'paul38@outlook.com'}
{'student_id': 39, 'name': 'Hannah39', 'email': 'hannah39@outlook.com'}
{'student_id': 40, 'name': 'Zane40', 'email': 'zane40@yahoo.com'}
{'student_id': 41, 'name': 'Ian41', 'email': 'ian41@outlook.com'}
{'student_id': 42, 'name': 'Quincy42', 'email': 'quincy42@gmail.com'}
{'student_id': 43, 'name': 'Quincy43', 'email': 'quincy43@gmail.com'}
{'student_id': 44, 'name': 'Tina44', 'email': 'tina44@outlook.com'}
{'student_id': 45, 'name': 'Xander45', 'email': 'xander45@yahoo.com'}
{'student_id': 46, 'name': 'Zane46', 'email': 'zane46@gmail.com'}
{'student_id': 47, 'name': 'Eva47', 'email': 'eva47@yahoo.com'}
{'student_id': 48, 'name': 'Leo48', 'email': 'leo48@outlook.com'}
{'student_id': 49, 'name': 'Uma49', 'email': 'uma49@school.edu'}
{'student_id': 50, 'name': 'Bob50', 'email': 'bob50@gmail.com'}
{'student_id': 51, 'name': 'Karen51', 'email': 'karen51@outlook.com'}
{'student_id': 52, 'name': 'Hannah52', 'email': 'hannah52@yahoo.com'}
{'student_id': 53, 'name': 'Bob53', 'email': 'bob53@outlook.com'}
{'student_id': 54, 'name': 'Leo54', 'email': 'leo54@yahoo.com'}
{'student_id': 55, 'name': 'Yara55', 'email': 'yara55@yahoo.com'}
{'student_id': 56, 'name': 'Eva56', 'email': 'eva56@school.edu'}
{'student_id': 57, 'name': 'Nina57', 'email': 'nina57@school.edu'}
{'student_id': 58, 'name': 'Eva58', 'email': 'eva58@yahoo.com'}
{'student_id': 59, 'name': 'Oscar59', 'email': 'oscar59@yahoo.com'}
{'student_id': 60, 'name': 'Yara60', 'email': 'yara60@gmail.com'}
{'student_id': 61, 'name': 'Oscar61', 'email': 'oscar61@gmail.com'}
{'student_id': 62, 'name': 'Rita62', 'email': 'rita62@gmail.com'}
{'student_id': 63, 'name': 'Victor63', 'email': 'victor63@yahoo.com'}
{'student_id': 64, 'name': 'Xander64', 'email': 'xander64@yahoo.com'}
{'student_id': 65, 'name': 'Hannah65', 'email': 'hannah65@school.edu'}
{'student_id': 66, 'name': 'Nina66', 'email': 'nina66@school.edu'}
{'student_id': 67, 'name': 'Victor67', 'email': 'victor67@outlook.com'}
{'student_id': 68, 'name': 'Karen68', 'email': 'karen68@school.edu'}
{'student_id': 69, 'name': 'Grace69', 'email': 'grace69@gmail.com'}
{'student_id': 70, 'name': 'Jack70', 'email': 'jack70@school.edu'}
{'student_id': 71, 'name': 'Nina71', 'email': 'nina71@outlook.com'}
{'student_id': 72, 'name': 'Ian72', 'email': 'ian72@gmail.com'}
{'student_id': 73, 'name': 'Grace73', 'email': 'grace73@yahoo.com'}
{'student_id': 74, 'name': 'Grace74', 'email': 'grace74@gmail.com'}
{'student_id': 75, 'name': 'Quincy75', 'email': 'quincy75@school.edu'}
{'student_id': 76, 'name': 'Oscar76', 'email': 'oscar76@school.edu'}
{'student_id': 77, 'name': 'Grace77', 'email': 'grace77@outlook.com'}
{'student_id': 78, 'name': 'Ian78', 'email': 'ian78@outlook.com'}
{'student_id': 79, 'name': 'Xander79', 'email': 'xander79@outlook.com'}
{'student_id': 80, 'name': 'Tina80', 'email': 'tina80@gmail.com'}
{'student_id': 81, 'name': 'Wendy81', 'email': 'wendy81@school.edu'}
{'student_id': 82, 'name': 'Karen82', 'email': 'karen82@outlook.com'}
{'student_id': 83, 'name': 'Leo83', 'email': 'leo83@outlook.com'}
{'student_id': 84, 'name': 'Bob84', 'email': 'bob84@school.edu'}
{'student_id': 85, 'name': 'Rita85', 'email': 'rita85@outlook.com'}
{'student_id': 86, 'name': 'Alice86', 'email': 'alice86@outlook.com'}
{'student_id': 87, 'name': 'Sam87', 'email': 'sam87@yahoo.com'}
{'student_id': 88, 'name': 'Wendy88', 'email': 'wendy88@yahoo.com'}
{'student_id': 89, 'name': 'Tina89', 'email': 'tina89@outlook.com'}
{'student_id': 90, 'name': 'Zane90', 'email': 'zane90@gmail.com'}
{'student_id': 91, 'name': 'Tina91', 'email': 'tina91@yahoo.com'}
{'student_id': 92, 'name': 'Wendy92', 'email': 'wendy92@gmail.com'}
{'student_id': 93, 'name': 'Quincy93', 'email': 'quincy93@gmail.com'}
{'student_id': 94, 'name': 'Eva94', 'email': 'eva94@school.edu'}
{'student_id': 95, 'name': 'Tina95', 'email': 'tina95@outlook.com'}
{'student_id': 96, 'name': 'Ian96', 'email': 'ian96@school.edu'}
{'student_id': 97, 'name': 'Mona97', 'email': 'mona97@gmail.com'}
{'student_id': 98, 'name': 'Leo98', 'email': 'leo98@school.edu'}
{'student_id': 99, 'name': 'Bob99', 'email': 'bob99@outlook.com'}
{'student_id': 100, 'name': 'Paul100', 'email': 'paul100@outlook.com'}

13. Create a program to count how many students are enrolled per course and display results in descending order.

In [56]:
pipeline = [
    {"$group": {"_id": "$course_name", "num_students": {"$sum": 1}}},
    {"$sort": {"num_students": -1}}
]

# Run aggregation on the collection
results = list(df_e.aggregate(pipeline))

# Print results
for doc in results:
    print(f"Course: {doc['_id']}, Students Enrolled: {doc['num_students']}")

Course: None, Students Enrolled: 401

14. Write a Python script that accepts a course name as input and returns all enrolled students with their grades.

In [66]:
course_name = input("Enter course name (partial allowed): ")

# find matching courses
for course in df_c.find({"course_name": {"$regex": course_name, "$options": "i"}}):
    print(f"\nStudents enrolled in {course['course_name']}:\n")
    enrollments = df_e.find({"course_id": course["course_id"]})
    found = False
    for e in enrollments:
        student = df_s.find_one({"student_id": e["student_id"]})
        if student:
            found = True
            print("ID:", student["student_id"],
                  "| Name:", student["name"],
                  "| Grade:", student["grade"])
    if not found:
        print("No students enrolled.")

Students enrolled in Mathematics:

ID: 7 | Name: Leo7 | Grade: A
ID: 10 | Name: Leo10 | Grade: A
ID: 14 | Name: Bob14 | Grade: C
ID: 16 | Name: Tina16 | Grade: A
ID: 17 | Name: Alice17 | Grade: B
ID: 19 | Name: Paul19 | Grade: A
ID: 26 | Name: Mona26 | Grade: D
ID: 28 | Name: Nina28 | Grade: B
ID: 30 | Name: Tina30 | Grade: A
ID: 46 | Name: Zane46 | Grade: C
ID: 48 | Name: Leo48 | Grade: B
ID: 58 | Name: Eva58 | Grade: A
ID: 61 | Name: Oscar61 | Grade: D
ID: 62 | Name: Rita62 | Grade: C
ID: 71 | Name: Nina71 | Grade: B
ID: 74 | Name: Grace74 | Grade: C
ID: 77 | Name: Grace77 | Grade: D
ID: 81 | Name: Wendy81 | Grade: A
ID: 89 | Name: Tina89 | Grade: C
ID: 91 | Name: Tina91 | Grade: D
ID: 92 | Name: Wendy92 | Grade: C
ID: 7 | Name: Leo7 | Grade: A
ID: 10 | Name: Leo10 | Grade: A
ID: 14 | Name: Bob14 | Grade: C
ID: 16 | Name: Tina16 | Grade: A
ID: 17 | Name: Alice17 | Grade: B
ID: 19 | Name: Paul19 | Grade: A
ID: 26 | Name: Mona26 | Grade: D
ID: 28 | Name: Nina28 | Grade: B
ID: 30 | Name: Tina30 | Grade: A
ID: 46 | Name: Zane46 | Grade: C
ID: 48 | Name: Leo48 | Grade: B
ID: 58 | Name: Eva58 | Grade: A
ID: 61 | Name: Oscar61 | Grade: D
ID: 62 | Name: Rita62 | Grade: C
ID: 71 | Name: Nina71 | Grade: B
ID: 74 | Name: Grace74 | Grade: C
ID: 77 | Name: Grace77 | Grade: D
ID: 81 | Name: Wendy81 | Grade: A
ID: 89 | Name: Tina89 | Grade: C
ID: 91 | Name: Tina91 | Grade: D
ID: 92 | Name: Wendy92 | Grade: C
ID: 1 | Name: Zane1 | Grade: C

Students enrolled in Mathematics:

ID: 7 | Name: Leo7 | Grade: A
ID: 10 | Name: Leo10 | Grade: A
ID: 14 | Name: Bob14 | Grade: C
ID: 16 | Name: Tina16 | Grade: A
ID: 17 | Name: Alice17 | Grade: B
ID: 19 | Name: Paul19 | Grade: A
ID: 26 | Name: Mona26 | Grade: D
ID: 28 | Name: Nina28 | Grade: B
ID: 30 | Name: Tina30 | Grade: A
ID: 46 | Name: Zane46 | Grade: C
ID: 48 | Name: Leo48 | Grade: B
ID: 58 | Name: Eva58 | Grade: A
ID: 61 | Name: Oscar61 | Grade: D
ID: 62 | Name: Rita62 | Grade: C
ID: 71 | Name: Nina71 | Grade: B
ID: 74 | Name: Grace74 | Grade: C
ID: 77 | Name: Grace77 | Grade: D
ID: 81 | Name: Wendy81 | Grade: A
ID: 89 | Name: Tina89 | Grade: C
ID: 91 | Name: Tina91 | Grade: D
ID: 92 | Name: Wendy92 | Grade: C
ID: 7 | Name: Leo7 | Grade: A
ID: 10 | Name: Leo10 | Grade: A
ID: 14 | Name: Bob14 | Grade: C
ID: 16 | Name: Tina16 | Grade: A
ID: 17 | Name: Alice17 | Grade: B
ID: 19 | Name: Paul19 | Grade: A
ID: 26 | Name: Mona26 | Grade: D
ID: 28 | Name: Nina28 | Grade: B
ID: 30 | Name: Tina30 | Grade: A
ID: 46 | Name: Zane46 | Grade: C
ID: 48 | Name: Leo48 | Grade: B
ID: 58 | Name: Eva58 | Grade: A
ID: 61 | Name: Oscar61 | Grade: D
ID: 62 | Name: Rita62 | Grade: C
ID: 71 | Name: Nina71 | Grade: B
ID: 74 | Name: Grace74 | Grade: C
ID: 77 | Name: Grace77 | Grade: D
ID: 81 | Name: Wendy81 | Grade: A
ID: 89 | Name: Tina89 | Grade: C
ID: 91 | Name: Tina91 | Grade: D
ID: 92 | Name: Wendy92 | Grade: C
ID: 1 | Name: Zane1 | Grade: C

15. Export the contents of the students table into a CSV file using Python.

In [60]:
students_data = list(df_s.find())

# Convert to DataFrame
df = pd.DataFrame(students_data)

# Optionally remove the MongoDB default '_id' column
if "_id" in df.columns:
    df = df.drop(columns=["_id"])

# Export to CSV
df.to_csv("students.csv", index=False)

print("Students data exported to students.csv successfully!")

Students data exported to students.csv successfully!

18. Handle exceptions in Python to gracefully catch duplicate entries (e.g., inserting a student with the same ID).

In [63]:
from pymongo import MongoClient, errors

try:
    df_s.insert_one(student)
    print("Student inserted successfully!")
except errors.DuplicateKeyError:
    print(f"Duplicate entry! Student with ID {student['student_id']} already exists.")

Duplicate entry! Student with ID 1 already exists.

19. Write a program to implement transactions in Python:
○ Insert a student
○ Enroll them in a course
○ Roll back if the second query fails

In [68]:
new_student = {"student_id": 10, "name": "John Doe", "age": 21}
new_enrollment = {"student_id": 10, "course_name": "Math", "grade": "A"}

try:
    # Start a session
    with client.start_session() as session:
        # Start a transaction
        with session.start_transaction():
            # Insert the student
            df_s.insert_one(new_student, session=session)
            
            # Simulate possible failure: uncomment next line to test rollback
            # raise Exception("Simulated failure during enrollment")
            
            # Enroll the student
            df_e.insert_one(new_enrollment, session=session)

    print("Transaction completed successfully!")

except Exception as e:
    print(f"Transaction aborted due to error: {e}")

Transaction aborted due to error: Transaction numbers are only allowed on a replica set member or mongos, full error: {'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on a replica set member or mongos', 'code': 20, 'codeName': 'IllegalOperation'}

20. Close the database connection safely in Python, ensuring both cursor and connection are properly closed.

In [69]:
client.close()

print("MongoDB connection closed safely.")

MongoDB connection closed safely.